id: bulk-builder-deposits
name: "Sustained unique 0x03 builder deposits per slot"
timeout: 4h
config:
  walletPrivkey: ''
  depositContract: '0x00000000219ab540356cBB839Cbe05303d7705Fa'
  depositAmount: 1
  totalDeposits: 65536
  perSlot: 128
  startSlot: 0 # asap

tasks:
- name: check_clients_are_healthy
  config:
    minClientCount: 1

- name: generate_child_wallet
  id: test_wallet
  config:
    walletSeed: bulk-builder-deposits
    prefundMinBalance: 120000000000000000000000   # 120000 ETH
  configVars:
    privateKey: walletPrivkey

- name: get_random_mnemonic
  id: test_mnemonic

- name: get_pubkeys_from_mnemonic
  id: builder_pubkeys
  configVars:
    mnemonic: "tasks.test_mnemonic.outputs.mnemonic"
    count: totalDeposits

- name: check_consensus_slot_range
  timeout: 30m
  configVars:
    minSlotNumber: startSlot

- name: generate_deposits
  id: deposit_batch
  config:
    startIndex: 0
    awaitReceipt: true
    awaitInclusion: true
  configVars:
    walletPrivkey: "tasks.test_wallet.outputs.childWallet.privkey"
    mnemonic: "tasks.test_mnemonic.outputs.mnemonic"
    depositContract: "depositContract"
    depositAmount: "depositAmount"
    limitTotal: totalDeposits
    limitPerSlot: perSlot
    indexCount: totalDeposits
    withdrawalCredentials: '| "0x03" + ("00" * 11) + (.tasks.test_wallet.outputs.childWallet.address | ltrimstr("0x"))'
